name: test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Updating files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        script: cd / | ls
